const { 
  CACHE_NAME, 
  VERSION, 
  SALT_ROTATION_INTERVAL, 
  ENCODING_MODES, 
  DEFAULT_ENCODING_MODE, 
  MAX_CACHE_AGE, 
  PREFETCH_CACHE_AGE,
  AD_BLOCK_FILTER_LIST_URL,
  HOSTS_FILE_URL,
  BOOKMARKS_STORAGE_KEY,
  PROXY_HISTORY_STORAGE_KEY,
  SETTINGS_STORAGE_KEY,
  SSL_CERT_FILE,
  SSL_KEY_FILE,
  HTTPS_PORT,
  TLS_PROTOCOLS,
  WEBSOCKET_TIMEOUT,
  WEBSOCKET_KEEP_ALIVE_INTERVAL,
  WEBSOCKET_PING_INTERVAL,
  WEBSOCKET_PONG_TIMEOUT,
  WEBSOCKET_SETTINGS,
  WEBRTC_SETTINGS,
  COOKIE_SCOPING_ENABLED,
  TAB_BAR_ENABLED,
  DARK_MODE_ENABLED,
  ANIMATE_SEARCH_BAR,
  AD_BLOCK_ENABLED,
  PREFETCH_HINTS_ENABLED,
  BROTLI_COMPRESSION_ENABLED,
  GZIP_COMPRESSION_ENABLED
} = require('./src/config/constants');

module.exports = {
  CACHE_NAME,
  VERSION,
  SALT_ROTATION_INTERVAL,
  ENCODING_MODES,
  DEFAULT_ENCODING_MODE,
  MAX_CACHE_AGE,
  PREFETCH_CACHE_AGE,
  AD_BLOCK_FILTER_LIST_URL,
  HOSTS_FILE_URL,
  BOOKMARKS_STORAGE_KEY,
  PROXY_HISTORY_STORAGE_KEY,
  SETTINGS_STORAGE_KEY,
  SSL_CERT_FILE,
  SSL_KEY_FILE,
  HTTPS_PORT,
  TLS_PROTOCOLS,
  WEBSOCKET_SETTINGS: {
    timeout: WEBSOCKET_TIMEOUT,
    keepAliveInterval: WEBSOCKET_KEEP_ALIVE_INTERVAL,
    pingInterval: WEBSOCKET_PING_INTERVAL,
    pongTimeout: WEBSOCKET_PONG_TIMEOUT
  },
  WEBRTC_SETTINGS,
  COOKIE_SCOPING_ENABLED,
  UI: {
    TAB_BAR_ENABLED,
    DARK_MODE_ENABLED,
    ANIMATE_SEARCH_BAR
  },
  AD_BLOCK: {
    ENABLED: AD_BLOCK_ENABLED,
    FILTER_LIST_URL: AD_BLOCK_FILTER_LIST_URL
  },
  PREFETCH: {
    ENABLED: PREFETCH_HINTS_ENABLED,
    CACHE_AGE: PREFETCH_CACHE_AGE
  },
  COMPRESSION: {
    BROTLI_ENABLED: BROTLI_COMPRESSION_ENABLED,
    GZIP_ENABLED: GZIP_COMPRESSION_ENABLED
  }
};