const { 
  CACHE_NAME, 
  VERSION, 
  SALT_ROTATION_INTERVAL, 
  ENCODING_MODES, 
  DEFAULT_ENCODING_MODE, 
  MAX_CACHE_AGE, 
  PREFETCH_CACHE_AGE,
  AD_BLOCK_FILTER_LIST_URL,
  HOSTS_FILE_URL,
  BOOKMARKS_STORAGE_KEY,
  PROXY_HISTORY_STORAGE_KEY,
  SETTINGS_STORAGE_KEY,
  SSL_CERT_FILE,
  SSL_KEY_FILE,
  HTTPS_PORT,
  TLS_PROTOCOLS,
  WEBSOCKET_TIMEOUT,
  WEBSOCKET_KEEP_ALIVE_INTERVAL,
  WEBSOCKET_PING_INTERVAL,
  WEBSOCKET_PONG_TIMEOUT,
  WEBSOCKET_SETTINGS,
  WEBRTC_SETTINGS,
  COOKIE_SCOPING_ENABLED,
  TAB_BAR_ENABLED,
  DARK_MODE_ENABLED,
  ANIMATE_SEARCH_BAR,
  AD_BLOCK_ENABLED,
  PREFETCH_HINTS_ENABLED,
  BROTLI_COMPRESSION_ENABLED,
  GZIP_COMPRESSION_ENABLED
} = require('./src/config/constants');

module.exports = {
  CACHE_NAME,
  VERSION,
  SALT_ROTATION_INTERVAL: SALT_ROTATION_INTERVAL || 3600000, // 1 hour default
  ENCODING_MODES: ENCODING_MODES || ['base64', 'xor'],
  DEFAULT_ENCODING_MODE: DEFAULT_ENCODING_MODE || 'xor',
  MAX_CACHE_AGE: MAX_CACHE_AGE || 604800000, // 7 days default
  PREFETCH_CACHE_AGE: PREFETCH_CACHE_AGE || 31536000000, // 1 year default
  AD_BLOCK_FILTER_LIST_URL: AD_BLOCK_FILTER_LIST_URL || 'https://raw.githubusercontent.com/brave/adblock-lists/master/ublock-origin-default.txt',
  HOSTS_FILE_URL: HOSTS_FILE_URL || 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts',
  BOOKMARKS_STORAGE_KEY: BOOKMARKS_STORAGE_KEY || 'nexus-bookmarks',
  PROXY_HISTORY_STORAGE_KEY: PROXY_HISTORY_STORAGE_KEY || 'nexus-proxy-history',
  SETTINGS_STORAGE_KEY: SETTINGS_STORAGE_KEY || 'nexus-settings',
  SSL_CERT_FILE: SSL_CERT_FILE || './certs/ssl-cert.pem',
  SSL_KEY_FILE: SSL_KEY_FILE || './certs/ssl-key.pem',
  HTTPS_PORT: HTTPS_PORT || 443,
  TLS_PROTOCOLS: TLS_PROTOCOLS || ['TLSv1.2', 'TLSv1.3'],
  WEBSOCKET_SETTINGS: {
    timeout: WEBSOCKET_TIMEOUT || 30000,
    keepAliveInterval: WEBSOCKET_KEEP_ALIVE_INTERVAL || 10000,
    pingInterval: WEBSOCKET_PING_INTERVAL || 25000,
    pongTimeout: WEBSOCKET_PONG_TIMEOUT || 10000
  },
  WEBRTC_SETTINGS: WEBRTC_SETTINGS || {
    iceCandidateScrubbing: true
  },
  COOKIE_SCOPING_ENABLED: COOKIE_SCOPING_ENABLED !== false,
  UI: {
    TAB_BAR_ENABLED: TAB_BAR_ENABLED !== false,
    DARK_MODE_ENABLED: DARK_MODE_ENABLED !== false,
    ANIMATE_SEARCH_BAR: ANIMATE_SEARCH_BAR !== false
  },
  AD_BLOCK: {
    ENABLED: AD_BLOCK_ENABLED !== false,
    FILTER_LIST_URL: AD_BLOCK_FILTER_LIST_URL
  },
  PREFETCH: {
    ENABLED: PREFETCH_HINTS_ENABLED !== false,
    CACHE_AGE: PREFETCH_CACHE_AGE
  },
  COMPRESSION: {
    BROTLI_ENABLED: BROTLI_COMPRESSION_ENABLED !== false,
    GZIP_ENABLED: GZIP_COMPRESSION_ENABLED !== false
  },
  LOGGING: {
    LEVEL: 'info',
    CONSOLE: true,
    FILE: './logs/nexus.log'
  },
  SECURITY: {
    SSL: {
      CERT_FILE: SSL_CERT_FILE,
      KEY_FILE: SSL_KEY_FILE
    },
    RATE_LIMITING: {
      ENABLED: true,
      WINDOW: 60000,
      MAX_REQUESTS: 100
    }
  },
  CACHE: {
    MAX_AGE: MAX_CACHE_AGE,
    TTL: 604800000 // 7 days default
  },
  SERVICE: {
    WORKER: {
      CACHE_API: true,
      MEMORY: 100 * 1024 * 1024 // 100MB
    }
  }
};