const CACHE_NAME = 'nexus-cache';
const DEFAULT_ENCODING = 'xor-base64';
const ROTATING_SALT_SIZE = 16;
const MAX_CACHE_AGE = 60 * 60 * 24 * 7; // 1 week
const PREFETCH_THRESHOLD = 1000; // 1 second
const AD_BLOCK_FILTER_LIST_URL = 'https://raw.githubusercontent.com/brave/adblock-lists/master/ublock-origin-default.txt';
const DEFAULT_TAB_TITLE = 'NEXUS Proxy';
const DEFAULT_TAB_ICON = 'https://example.com/favicon.ico';
const SUPPORTED_ENCODINGS = ['xor-base64', 'base64'];
const REQUEST_HEADER_REWRITE_LIST = ['Content-Security-Policy', 'Strict-Transport-Security', 'X-Frame-Options'];
const RESPONSE_HEADER_REWRITE_LIST = ['Content-Security-Policy', 'Strict-Transport-Security', 'X-Frame-Options'];
const SOURCE_MAP_URL_REGEX = /\#(.*)\.map$/;